function g = R60VNAdataplot (freqVectorPath, csvFilePath)

freqVectorPath = "C:\Users\reuelgroup\Desktop\R60\FreqVector.csv";
csvFilePath = "C:\Users\reuelgroup\Desktop\R60\Scat_data_1.csv";
F = csvread(freqVectorPath);



    d = csvread(csvFilePath);
    d = d(:,2); % only S11
    
    [ymin, yind] = min(d);
    xmin = F(yind);
    
    minFrange = F(F>xmin-0.5e6 & F<xmin+0.5e6,:);
    minSrange = d(F>xmin-0.5e6 & F<xmin+0.5e6,:);
    p = polyfit(minFrange,minSrange,2);
    newF = linspace(min(minFrange),max(minFrange),length(minFrange)*10);
    newS = polyval(p,newF);
    [ymin2, yind2] = min(newS);
    xmin2 = newF(yind2);

%%%%%%%%%%%%%%%% Fit


xl = xlsread ("C:\My Work\Dynamic Heat Experiment\Spring 2023\Incubator Experiment\Calibration Curve Exp\1 Tag New Exp\Final Peak.xlsx");

% for i=24.5:0.5:44
%   
%     peak = xlsread ("C:\My Work\Dynamic Heat Experiment\Spring 2023\Incubator Experiment\Calibration Curve Exp\1 Tag\" + num2str(i) + "\Peaks.xlsx");
%     
%     
%   
% end

x = xl(:,2)/1e+6;
y = xl(:,1);

%plot(y,x, '-o');




%CREATEFIT(Y,X)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : y
%      Y Output: x
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 09-Mar-2023 13:56:18


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( y, x );

% Set up fittype and options.
ft = fittype( 'power2' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [155.262156017685 -0.03826538838837 -0.00188949571206296];

% Fit model to data.
[fitresult, gof] = fit( yData, xData, ft, opts );

g = fitresult(xmin2/(1e+6));


% Plot fit with data.
 %figure( 'Name', 'untitled fit 1' );
% h = plot( fitresult, xData, yData );
% legend( h, 'Frequency v/s Tempearture', 'Fitted Curve', 'Location', 'NorthEast', 'Interpreter', 'none' );
% % Label axes
% xlabel('Temperature (C^{\circ})');
% ylabel( 'Frequency (MHz)', 'Interpreter', 'none' );
% grid off


end








